services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: masters-glossary-frontend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


